[tool.poetry]
name = "marketsai"
version = "0.1.0"
description = "marketsAI is a modular framework designed to simulate economies that are composed of multiple interconnected markets."
authors = ["Matias Covarrubias <matias.covarrubias@nyu.edu>"]
maintainers = ["Matias Covarrubias <matias.covarrubias@nyu.edu>", "Agustin Covarrubias <agucova@uc.cl>"]
readme = "README.md"
homepage = "https://marketsai.org"
repository = "https://github/marketsAI/marketsAI"

[tool.poetry.urls]
issues = "https://github.com/marketsAI/marketsAI/issues"

[tool.poetry.dependencies]
python = "^3.8"
gym = "^0.18.0"
prettytable = "^2.0.0"
numpy = "^1.20.0"
matplotlib = "^3.3.4"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
